version: '3.8'

services:
  dbcontainer: 
    image: mysql:5.7
    container_name: dbcontainer
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}